apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-exporter
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: nats-exporter
  endpoints:
    - port: metrics
      interval: 15s
