{
 "title": "Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Avg (cluster, 5m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "CPU Avg (cluster over time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))"
    }
   ]
  },
  {
   "title": "Memory used in cluster",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (avg(node_memory_MemAvailable_bytes) / avg(node_memory_MemTotal_bytes)))",
     "legendFormat": "{{cluster memory usage}}"
    }
   ]
  },
  {
   "title": "Network ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device!~\"lo\"}[5m])) / 1024 / 1024",
     "legendFormat": "out bytes"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device!~\"lo\"}[5m])) / 1024 / 1024",
     "legendFormat": "in bytes"
    }
   ]
  },
  {
   "title": "Cluster disk usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  1 - (\n    sum(node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay|squashfs\"})\n  / sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay|squashfs\"})\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}