apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.20.4
    helm:
      values: |
        installCRDs: true
        certController:
          create: false
  spec:
    ignoreDifferences:
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jsonPointers:
          - /status
      - group: apiextensions.k8s.io
        kind: CustomResourceDefinition
        jqPathExpressions:
          - .metadata.annotations
          - .metadata.managedFields
          - .spec.conversion.webhook.clientConfig.caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true