apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://repo.helmforge.dev
    chart: ntfy
    targetRevision: 0.1.0
    helm:
      values: |
        image:
          tag: "v2.22.0"

        ntfy:
          baseUrl: "http://192.168.1.19:30880"
          authDefaultAccess: "read-write"
          behindProxy: false

        persistence:
          enabled: true
          size: 2Gi
          storageClass: longhorn

        service:
          type: NodePort
          port: 80

        ingress:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: ntfy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true