apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://repo.helmforge.dev
    chart: ntfy
    targetRevision: 1.1.2
    helm:
      values: |
        image:
          tag: "v2.22.0"

        ntfy:
          baseUrl: "https://ntfy.bru-li.me"
          authDefaultAccess: "deny-all"
          behindProxy: true
          extraConfig: |
            auth-file: /var/cache/ntfy/user.db
            cache-file: /var/cache/ntfy/cache.db
            attachment-cache-dir: /var/cache/ntfy/attachments

        persistence:
          enabled: true
          size: 2Gi
          storageClass: longhorn

        service:
          type: ClusterIP
          port: 80

        ingress:
          enabled: true
          ingressClassName: cloudflare
          hosts:
            - host: ntfy.bru-li.me
              paths:
                - path: /
                  pathType: Prefix
          tls: []

  destination:
    server: https://kubernetes.default.svc
    namespace: ntfy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true