apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntfy
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://repo.helmforge.dev
    chart: ntfy
    targetRevision: 0.1.0
    helm:
      values: |
        service:
          type: NodePort
          ports:
            http:
              port: 80
              nodePort: 30880

        ingress:
          enabled: false

        persistence:
          enabled: true
          storageClass: longhorn
          size: 1Gi

        ntfy:
          config:
            base-url: "http://192.168.1.19:30880"
            behind-proxy: false
            enable-login: true
            enable-signup: false
            cache-file: "/var/cache/ntfy/cache.db"
            attachment-cache-dir: "/var/cache/ntfy/attachments"

  destination:
    server: https://kubernetes.default.svc
    namespace: ntfy

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true