---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations: {argocd.argoproj.io/sync-wave: "20"}
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: v1.9.2
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false

        defaultSettings:
          defaultReplicaCount: 2
          defaultDataPath: /var/lib/longhorn

        persistence:
          defaultClass: true
          defaultFsType: ext4

        metrics:
          serviceMonitor:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
