---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.9.2
    helm:
      values: |
        metrics:
          enabled: false

        defaultSettings:
          defaultReplicaCount: 2
          createDefaultDiskLabeledNodes: true

        preUpgradeChecker:
                 nodeSelector:
                   kubernetes.io/arch: arm64
                 tolerations:
                   - operator: "Exists"

        # Ingress senzill (HTTP) per evitar TLS fins que tot funcione
        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web
          host: longhorn.192.168.1.14.nip.io
          tls: false
          path: /
          pathType: Prefix
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
