---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: ~1.6.0
    helm:
      values: |
        defaultSettings:
          defaultReplicaCount: 1
          allowCollectingLonghornUsageMetrics: false
          defaultDataPath: /var/lib/longhorn
        persistence:
          defaultClass: true
          defaultFsType: ext4
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
