apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd # Or your Argo CD namespace
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.5.3 # Replace with your desired Longhorn version
    helm:
      # Add any custom values here, e.g., for enabling preUpgradeChecker
      values: |
        preUpgradeChecker:
          jobEnabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system # The namespace where Longhorn will be installed
