apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-controller
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi

  source:
    repoURL: https://qonstrukt.github.io/helm-charts/
    chart: unifi-controller
    targetRevision: 2.6.1
    helm:
      releaseName: unifi-controller
      parameters:
        - name: persistence.storageClass
          value: longhorn
        - name: persistence.storageClassName
          value: longhorn
        - name: persistence.data.storageClass
          value: longhorn
        - name: persistence.data.storageClassName
          value: longhorn
        - name: persistence.backup.storageClass
          value: longhorn
        - name: persistence.backup.storageClassName
          value: longhorn
        - name: backup.storageClass
          value: longhorn
        - name: backup.storageClassName
          value: longhorn
      values: |
        service:
          type: ClusterIP
        persistence:
          enabled: true
          size: 10Gi
        backup:
          enabled: false

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
