apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-controller
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: unifi

  source:
    repoURL: https://qonstrukt.github.io/helm-charts/
    chart: unifi-controller
    targetRevision: 2.6.1
    helm:
      releaseName: unifi-controller
      values: |
        service:
          type: ClusterIP

        persistence:
          enabled: true
          size: 10Gi
          storageClassName: longhorn

        # si el chart separa data/backup, afegeix també això:
#         backup:
#           enabled: true
#           size: 10Gi
#           storageClassName: longhorn

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
