apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi-controller
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: unifi

  source:
    repoURL: https://qonstrukt.github.io/helm-charts/
    chart: unifi-controller
    targetRevision: 2.6.1
    helm:
      releaseName: unifi-controller
      values: |
        service:
          type: ClusterIP

        persistence:
          enabled: true
          size: 10Gi
          storageClassName: longhorn

        # Ports interns típics (no exposats fora del cluster)
        ports:
          https:
            port: 8443
          inform:
            port: 8080
          stun:
            port: 3478

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            memory: 1Gi

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
