apiVersion: v1
kind: Secret
metadata:
  name: influxdb-auth
  namespace: influxdb
type: Opaque
stringData:
  admin-password: hAVE1DREAM
  admin-token: khJm7MLiTY78tA12fV4caop5g1XJ5ZAjVVsoUVWjiPTgyddI61pGa1qhCT3GZYfm