---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats-exporter
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: monitoring
spec:
  project: default
  source:
    repoURL: https://github.com/bruli/k3s-infra.git
    targetRevision: main
    path: infra/nats-exporter
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
