apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-metrics
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://kubernetes-sigs.github.io/metrics-server/
      chart: metrics-server
      targetRevision: "3.12.1"
      helm:
        valueFiles:
          - $values/apps/k3s-metrics/values.yaml
    - repoURL: https://github.com/bruli/k3s-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
