tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"

nodeSelector:
  kubernetes.io/arch: arm64
  kubernetes.io/os: linux

hostNetwork: false
hostPID: false

service:
  port: 9100
  targetPort: 9100
  portName: metrics
