apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: nats
  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts
    chart: nats
    targetRevision: 2.12.1
    helm:
        values: |
            config: |
                port: 4222
                http: 8222          # 👈 habilita /varz, /connz, /subsz
                # (opcional) cluster:
                # cluster: { port: 6222 }
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
