apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nats
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: nats

  source:
    repoURL: https://nats-io.github.io/k8s/helm/charts
    chart: nats
    targetRevision: 2.12.1
    helm:
      values: |
        config:
          cluster:
            enabled: true
            replicas: 3
            routeURLs:
              user: << $NATS_USER >>
              password: << $NATS_PASSWORD >>

          jetstream:
            enabled: true
            fileStore:
              enabled: true
              dir: /data
              pvc:
                enabled: true
                size: 10Gi
                storageClassName: longhorn

          monitor:
            enabled: true
            port: 8222

          merge:
            authorization:
              users:
                - user: << $NATS_USER >>
                  password: << $NATS_PASSWORD >>

        container:
          merge:
            env:
              - name: NATS_USER
                valueFrom:
                  secretKeyRef:
                    name: nats-auth
                    key: NATS_USER
              - name: NATS_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: nats-auth
                    key: NATS_PASSWORD

        reloader:
          enabled: false

        service:
          merge:
            spec:
              type: NodePort
              ports:
                - name: nats
                  port: 4222
                  protocol: TCP
                  targetPort: nats
                  nodePort: 31222
                - name: monitor
                  port: 8222
                  protocol: TCP
                  targetPort: monitor

        natsBox:
          enabled: true
          contexts:
            default:
              merge:
                user: << $NATS_USER >>
                password: << $NATS_PASSWORD >>
          container:
            merge:
              env:
                - name: NATS_USER
                  valueFrom:
                    secretKeyRef:
                      name: nats-auth
                      key: NATS_USER
                - name: NATS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: nats-auth
                      key: NATS_PASSWORD

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true