apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alerter
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: apps
spec:
  project: default
  source:
    repoURL: https://github.com/bruli/alerter.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
