apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mycalendar-google-secret
  namespace: mycalendar
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: google-secret
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: telegram/google
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: telegram/google
        property: client_secret