apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watersystem-ml-postgres-secret
  namespace: watersystem-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgres-watersystem-ml-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres/watersystem-ml
        property: DB_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres/watersystem-ml
        property: DB_PASSWORD