apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watersystem-ml-influxdb-secret
  namespace: watersystem-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: influxdb-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: influxdb/bonsai
        property: token
    - secretKey: org
      remoteRef:
        key: influxdb/bonsai
        property: org
    - secretKey: bucket
      remoteRef:
        key: influxdb/bonsai
        property: bucket