apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watersystem-ml-watersystem-secret
  namespace: watersystem-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: watersystem-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: waterSystem
        property: auth_token
