apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watersystem-ml-telegram-secret
  namespace: watersystem-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: telegram-secret
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: telegram/waterSystem
        property: token
    - secretKey: chat_id
      remoteRef:
        key: telegram/waterSystem
        property: chat_id