apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: watersystem-ml-ntfy-secret
  namespace: watersystem-ml
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ntfy-secret
    creationPolicy: Owner
  data:
    - secretKey: user
      remoteRef:
        key: ntfy/waterSystem
        property: user
    - secretKey: password
      remoteRef:
        key: ntfy/waterSystem
        property: password