adminUser: "admin"
adminPassword: "changeme"

service:
  type: NodePort
  nodePort: 32000

# persistence:
#   enabled: true
#   size: 2Gi
#   storageClassName: local-path

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.prometheus.svc.cluster.local
        isDefault: true

dashboards:
  default:
    # Dashboard simple amb mitjana de CPU del clúster
    cluster-cpu-average:
      json: |-
        {
          "id": null,
          "uid": null,
          "title": "Cluster CPU Average (5m)",
          "schemaVersion": 38,
          "version": 1,
          "refresh": "10s",
          "time": { "from": "now-15m", "to": "now" },
          "panels": [
            {
              "type": "stat",
              "title": "CPU Avg (cluster, 5m)",
              "id": 1,
              "datasource": "Prometheus",
              "targets": [
                {
                  "refId": "A",
                  "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))",
                  "instant": true
                }
              ],
              "fieldConfig": {
                "defaults": { "unit": "percent", "decimals": 1 }
              },
              "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 }
            },
            {
              "type": "timeseries",
              "title": "CPU Avg (cluster over time)",
              "id": 2,
              "datasource": "Prometheus",
              "targets": [
                { "refId": "A", "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])))" }
              ],
              "fieldConfig": {
                "defaults": { "unit": "percent", "decimals": 1 }
              },
              "gridPos": { "h": 8, "w": 16, "x": 8, "y": 0 }
            }
          ]
        }

    # Dashboard complet del node-exporter
    node-exporter-full:
      gnetId: 1860
      revision: 31
      datasource: Prometheus

    # Dashboard de kube-state-metrics
    kube-state-metrics:
      gnetId: 13332
      revision: 1
      datasource: Prometheus
