alertmanager:
  enabled: true

server:
  persistentVolume:
    enabled: true
    size: 2Gi
    storageClass: local-path
  service:
    type: ClusterIP
  serverFiles:
    prometheus.yml:
      global:
        scrape_interval: 15s
        evaluation_interval: 30s
      scrape_configs:
        - job_name: 'kube-state-metrics'
          static_configs:
            - targets:
                - 'kube-state-metrics.kube-system.svc.cluster.local:8080'

        - job_name: 'node-exporter'
          kubernetes_sd_configs:
            - role: endpoints
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_name]
              action: keep
              regex: prometheus-node-exporter
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              action: keep
              regex: metrics

pushgateway:
  enabled: false
